"""added email_otp columns

Revision ID: 5de6a6bb6056
Revises: 0bbc6170abcd
Create Date: 2025-11-26 13:37:55.920498

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5de6a6bb6056'
down_revision: Union[str, Sequence[str], None] = '0bbc6170abcd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email_otp_code', sa.String(length=6), nullable=True))
    op.add_column('users', sa.Column('email_otp_expires_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'email_otp_expires_at')
    op.drop_column('users', 'email_otp_code')
    # ### end Alembic commands ###
